# Copyright © 2025-present Jiangsu Qiantong Technology Co., Ltd.
#
# This file is part of qKnow Intelligent Agent Building Platform (Open Source Edition).
#
# qKnow is licensed under Apache License 2.0 with additional qKnow terms.
# You may use qKnow for commercial purposes, but you may not remove, hide,
# modify, or replace the qKnow logo, copyright notices, license notices,
# or attribution information without a separate commercial license.
#
# White-label use, OEM distribution, rebranding, or presenting qKnow as
# another product requires separate commercial authorization from
# Jiangsu Qiantong Technology Co., Ltd.
#
# Business License: https://community.qknow.ai/business/policy.html
# See the LICENSE file in the project root for full license information.

services:
  api:
    privileged: true
    image: ${QKNOW_HUB}/qknow-server-ce:${QKNOW_TAG}
    restart: always
    profiles: [ "qknow", "base" ]
    env_file: .env
    environment:
      - TZ=Asia/Shanghai
      - SPRING_CONFIG_LOCATION=file:/usr/app/jar/
      - SPRING_CONFIG_NAME=application,application-file,application-ext,application-kmc,application-neo4j,application-thirdparty,application-ai
    # 如需覆盖端口也可加：
    #    ports:
    #      - "8080:8080"
    mac_address: 28-C5-D2-B7-FC-F7
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./qKnow/indexDir:/usr/app/jar/indexDir
      - ./qKnow/server/logs:/usr/app/jar/logs
      - ./qKnow/server/upload:/usr/app/jar/upload
      - ./qKnow/server/application-prod.yml:/usr/app/jar/application-prod.yml
      - ./qKnow/server/application-ext-prod.yml:/usr/app/jar/application-ext-prod.yml
      - ./qKnow/server/application-file-prod.yml:/usr/app/jar/application-file-prod.yml
      - ./qKnow/server/application-ai-prod.yml:/usr/app/jar/application-ai-prod.yml
      - ./qKnow/server/application-neo4j-prod.yml:/usr/app/jar/application-neo4j-prod.yml
      - ./qKnow/server/application-kmc-prod.yml:/usr/app/jar/application-kmc-prod.yml
      - ./qKnow/server/application-thirdparty-prod.yml:/usr/app/jar/application-thirdparty-prod.yml
      - ./qKnow/server/application.yml:/usr/app/jar/application.yml
#      - ./qKnow/server/qKnow.key:/usr/app/jar/qKnow.key
    depends_on:
      redis:
        condition: service_healthy
      mysql57:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    networks:
      - qknownet
    extra_hosts:
      - "host.docker.internal:host-gateway"
